name: "Conftest"
description: "Runs conftest test"
inputs: 
  files:
    description: "Files for Conftest to test"
    required: true
  policy:
    description: "Where to find the policy folder or file"
    default: "policy"
  output:
    description: "Output format for results"
    default: "stdout"
runs:
  using: 'docker'
  image: 'docker://openpolicyagent/conftest:v0.62.0' 
  entrypoint: sh
  args:
  - -c
  - conftest test -o "${{ inputs.output }}" -p "${{ inputs.policy }}" ${{ inputs.files }} 
