name: Conftest Test
on:
  workflow_call:
    inputs:
      topstack-version:
        required: true
        type: string
jobs:
  conftest-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: kordian7/workflow-repo
          ref: main
      - name: Download values.yaml
        id: artifact-download
        uses: actions/download-artifact@v4
        with:
          name: values
          path: .
      - name: test
        uses: ./.github/actions/conftest
        with:
          files: values.yaml
          policy: conftest-policies/${{ inputs.config-path }}/policy.rego
      - run: echo "This job's status is ${{ job.status }}."
